name: CI

on:
  pull_request:
    branches: [master]

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label }}'
  cancel-in-progress: true

jobs:
  CI:
    name: CI
    uses: rafflebox-technologies-inc/github-workflows/.github/workflows/ci.yml@v1
    with:
      commit: ${{ github.sha }}

    secrets:
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
